### ISSUE TITLE
g++ error

### ISSUE THREAD

**Issue by biexiangduo** [lefticus/cpp_starter_project#13]
ubuntu 16.04

~/cpp_starter_project$ g++ main.cpp
main.cpp: In function ‘int main()’:
main.cpp:6:4: warning: lambda capture initializers only available with -std=c++14 or -std=gnu++14
   [out = std::ref(std::cout << "Hello ")]() { out.get() << "World\n"; }
    ^
main.cpp:6:10: error: ‘ref’ is not a member of ‘std’
   [out = std::ref(std::cout << "Hello ")]() { out.get() << "World\n"; }
          ^
main.cpp: In lambda function:
main.cpp:6:47: error: ‘out’ was not declared in this scope
   [out = std::ref(std::cout << "Hello ")]() { out.get() << "World\n"; }
                                               ^
main.cpp: In function ‘int main()’:
main.cpp:6:71: warning: lambda expressions only available with -std=c++11 or -std=gnu++11
   [out = std::ref(std::cout << "Hello ")]() { out.get() << "World\n"; }

is this a version error? how could i correct.

**Comment by ddalcino** [comment]
For this project to compile as is, you’ll need g++ version 7 or later installed. With some edits to the warnings specified by Cmakelists.txt, you might be able to get it running with g++ 5, but I wouldn’t recommend it.

You could try installing g++7 from the terminal like this:
`$ sudo apt-get install g++-7 gcc-7`
If that doesn’t work, you may need to add some PPAs. Try googling ‘Ubuntu 16 install g++7’; you should be able to find that easily.

Then you just need to make sure that cmake knows that it needs to use g++-7 instead of the older version.

**Comment by biexiangduo** [comment]
thanks so much for your help

**Comment by ddalcino** [comment]
Would it be appropriate to mark this issue “closed”?

**Comment by lefticus** [comment]
Thank you @ddalcino , I'm closing this one.

I think it would be good to put some version checks into the code base, I do have some CMake scripts for that somewhere I think.
