### ISSUE TITLE
Output bug (vscode)

### ISSUE THREAD

**Issue by parequena** [lefticus/cpp_starter_project#137]
¡Hello!
I've tryed this template to a personal project and when I have an error on my code,  vscode output shows some unreadable characters.

```
[build]  #include [01;31m[K<SDL2/SDL.h>[m[K
[build]           [01;31m[K^~~~~~~~~~~~[m[K
```

I've checked all fonts, and I dones't look to solve anything.
Those characters just appears using this template, and I can't fix it.

If someone can help me please.

**Comment by ddalcino** [comment]
These are [ANSI escape codes for setting the text color to red](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors). If you're using a terminal that isn't ANSI compliant, you see these characters instead of colored text.

Is this part of an error message telling you that the compiler is unable to locate the SDL2 headers?

**Comment by parequena** [comment]
No, I've just added some characters to introduce that error, actually template works perfect, but when I get any error, I got those ANSI escape codes, so I'll look to disable them.
