### ISSUE TITLE
Test logs are overwritten when called with `ctest`

### ISSUE THREAD

**Issue by avitase** [lefticus/cpp_starter_project#61]
When unit tests are executed with `ctest`, each `TEST_CASE` is invoked separately but the logs are all written to the same xml file. Say there are two `TEST_CASE`s with the same target `tests`, then the xml logs of both is written to `tests.xml` (as configured in [test/CMakeLists.txt](https://github.com/lefticus/cpp_starter_project/blob/c60ca61971e5998d71afdfbabd2472f331b43fec/test/CMakeLists.txt#L28)) and the latter eventually overwrites the logs of the former. So the problem is the hard coded filename `--out=test.xml` but I am not sure how to fix this properly. (You can use `ctest -V` to see the invoked commands.)

**Comment by ToppDev** [comment]
This problem was solved with the new catch2 version 2.13.3 ([Issue](https://github.com/catchorg/Catch2/issues/1946))

They added new config options for the `catch_discover_tests` routine ([Dokumentation](https://github.com/catchorg/Catch2/blob/devel/docs/cmake-integration.md))
```
[REPORTER reporter]
[OUTPUT_DIR dir]
[OUTPUT_PREFIX prefix]
[OUTPUT_SUFFIX suffix]
```
With these options you can create multiple files and then merge them afterwards with `xml_grep`, e.g.
```
xml_grep --pretty_print indented --wrap '' --descr '' --cond "Catch" build/test/*.xml > test_results.xml
``` 

I made a fork from the project and committed the changes into a new branch. I just don't know how GitHub Pull requests work. So I could not make one.
https://github.com/ToppDev/cpp_starter_project/commit/0c2362d7903c2e83f614866e3461960ee00994aa
