### ISSUE TITLE
CMake doesn't require GCC 8 or later, but uses a GCC-8-or-later option

### ISSUE THREAD

**Issue by eyalroz** [lefticus/cpp_starter_project#9]
The compilation invokes g++ with `-Wduplicated-branches`, which was only introduced in GCC 8.x, it seems. My distribution uses GCC 6.x, so my build fails.

Either GCC 6.x (and 7.x I think) should be unsupported, or the warning needs to be dropped for GCC 8.x

**Comment by ddalcino** [comment]
I made a [pull request](https://github.com/lefticus/cpp_starter_project/pull/10) that has some relevance to this issue. 

On my branch, I specified that Travis-CI should use gcc-7 instead of gcc-5. This causes the vm to install GCC 7.4.0, which handles all of the specified compiler flags without any problem, and the build completes successfully. I claim that this is evidence that GCC 7.4.0 (I can't speak to version 7.3.x and below) supports the `-Wduplicated-branches` flag.

As far as I can tell, a CMakeLists.txt file does not have any way to tell you what compiler version you should be using: it either builds or it fails.

Maybe we could add a command line option that conditionally adds warning flags based on what compiler you specify? Alternately, you could use `try_compile` to work out what warning flags are available on whatever compiler you're using, and set the warning flags accordingly.

**Comment by ddalcino** [comment]
Since the [readme](https://github.com/lefticus/cpp_starter_project#necessary-dependencies) now recommends gcc 7 or above, I think this is resolved. If you disagree, you are welcome to reopen this.
