### ISSUE TITLE
cmake system MSYS is not supported by conan

### ISSUE THREAD

**Issue by ugurmelihsurme** [lefticus/cpp_starter_project#97]
**### When the project is compiled with msys2, the following outputs are seen. How could it be fixed.**

Eclipse version is set to 3.6 (Helios). Adjust CMAKE_ECLIPSE_VERSION if this is wrong.
 ccache found and enabled
 Conan: checking conan executable
 Conan: Found program /d/Programs/Python39/Scripts/conan.exe
 Conan: Version found Conan version 1.30.2

 Conan: Adding bincrafters remote repository (https://api.bintray.com/conan/bincrafters/public-conan)
 Conan: Automatic detection of conan settings from cmake
 CMake Error at build/conan.cmake:112 (message):
   **cmake system MSYS is not supported by conan.**  Use one of
   Windows;Linux;Macos;Android;iOS;FreeBSD;WindowsStore
 Call Stack (most recent call first):
   build/conan.cmake:496 (conan_cmake_settings)
   cmake/Conan.cmake:16 (conan_cmake_run)
   CMakeLists.txt:78 (run_conan)

 Configuring incomplete, errors occurred!
 See also "/d/github/cpp_starter_project/build/CMakeFiles/CMakeOutput.log".

**Comment by ddalcino** [comment]
I'm sorry to hear you're having trouble building the project.

I think this issue is related to https://github.com/conan-io/conan/issues/5663. Until that issue is resolved, I don't think that Conan will ever run properly from within MSYS. 

On Windows, you should be able to build the project from `cmd.exe` or from Powershell; the [README](https://github.com/lefticus/cpp_starter_project/blob/master/README.md) should help you to get everything set up. Keep in mind that you can use the `CC` and `CXX` environment variables to point to whatever compilers you wish; this includes the compilers that you can install with MSYS.

I hope this helps, and that you can get everything set up properly!

**Comment by lefticus** [comment]
I'm going to close this issue, as it is not specific to this project, but is intrinsic to issues with conan/msys. Thank you for triaging @ddalcino
